apiVersion: skaffold/v2beta10
kind: Config
metadata:
  name: tb-tweet-ingestion-streaming
build:
  artifacts:
  - image: gcr.io/psychic-outcome-303709/tb-ingest-tweets-streaming
    context: .
    docker: {}
deploy:
  kubectl:
    manifests:
    - deployment.yaml
    - service-account-key.yaml
